/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/layout/AdminHeader.vue')['default']
    AdminLayout: typeof import('./src/components/layout/AdminLayout.vue')['default']
    AiSearchBar: typeof import('./src/components/showcase/AiSearchBar.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    ArticleContentBlocks: typeof import('./src/components/insights/ArticleContentBlocks.vue')['default']
    ArticleContentBlocksEditor: typeof import('./src/components/admin/articles/ArticleContentBlocksEditor.vue')['default']
    ArticleLike: typeof import('./src/components/insights/ArticleLike.vue')['default']
    ArticleQuickImport: typeof import('./src/components/admin/articles/ArticleQuickImport.vue')['default']
    ArticleRichText: typeof import('./src/components/insights/ArticleRichText.vue')['default']
    ArticleShare: typeof import('./src/components/insights/ArticleShare.vue')['default']
    ArticleSubscription: typeof import('./src/components/insights/ArticleSubscription.vue')['default']
    AuthModal: typeof import('./src/components/auth/AuthModal.vue')['default']
    BackToTop: typeof import('./src/components/layout/BackToTop.vue')['default']
    CaseCard: typeof import('./src/components/showcase/CaseCard.vue')['default']
    CaseDetailModal: typeof import('./src/components/admin/CaseDetailModal.vue')['default']
    CaseFormModal: typeof import('./src/components/admin/CaseFormModal.vue')['default']
    CaseFormSection: typeof import('./src/components/admin/CaseFormSection.vue')['default']
    CaseMetricsCards: typeof import('./src/components/admin/CaseMetricsCards.vue')['default']
    CaseShowcase: typeof import('./src/components/showcase/CaseShowcase.vue')['default']
    CaseTableSection: typeof import('./src/components/admin/CaseTableSection.vue')['default']
    FrontHeader: typeof import('./src/components/layout/FrontHeader.vue')['default']
    HomeCarouselSection: typeof import('./src/components/home/HomeCarouselSection.vue')['default']
    HomeContactCtaSection: typeof import('./src/components/home/HomeContactCtaSection.vue')['default']
    HomeHeroSection: typeof import('./src/components/home/HomeHeroSection.vue')['default']
    HomeIndustryWeatherSection: typeof import('./src/components/home/HomeIndustryWeatherSection.vue')['default']
    HomeInsightsSection: typeof import('./src/components/home/HomeInsightsSection.vue')['default']
    HomeLegacyCasesSection: typeof import('./src/components/home/HomeLegacyCasesSection.vue')['default']
    HomePersonasSection: typeof import('./src/components/home/HomePersonasSection.vue')['default']
    HomePromoCarouselSection: typeof import('./src/components/home/HomePromoCarouselSection.vue')['default']
    HomeServiceDock: typeof import('./src/components/home/HomeServiceDock.vue')['default']
    HomeServiceGuideSection: typeof import('./src/components/home/HomeServiceGuideSection.vue')['default']
    HomeServicesSection: typeof import('./src/components/home/HomeServicesSection.vue')['default']
    IndustryWeatherCard: typeof import('./src/components/home/IndustryWeatherCard.vue')['default']
    KqcBadge: typeof import('./src/components/ui/KqcBadge.vue')['default']
    KqcBreadcrumb: typeof import('./src/components/ui/KqcBreadcrumb.vue')['default']
    KqcButton: typeof import('./src/components/ui/KqcButton.vue')['default']
    KqcCard: typeof import('./src/components/ui/KqcCard.vue')['default']
    KqcCheckbox: typeof import('./src/components/ui/KqcCheckbox.vue')['default']
    KqcInput: typeof import('./src/components/ui/KqcInput.vue')['default']
    KqcMessage: typeof import('./src/components/ui/KqcMessage.vue')['default']
    KqcModal: typeof import('./src/components/ui/KqcModal.vue')['default']
    KqcProgressBar: typeof import('./src/components/ui/KqcProgressBar.vue')['default']
    KqcRadio: typeof import('./src/components/ui/KqcRadio.vue')['default']
    KqcSelect: typeof import('./src/components/ui/KqcSelect.vue')['default']
    KqcSkeleton: typeof import('./src/components/ui/KqcSkeleton.vue')['default']
    KqcStatGauge: typeof import('./src/components/ui/KqcStatGauge.vue')['default']
    KqcSwitch: typeof import('./src/components/ui/KqcSwitch.vue')['default']
    KqcTable: typeof import('./src/components/ui/KqcTable.vue')['default']
    KqcTag: typeof import('./src/components/ui/KqcTag.vue')['default']
    KqcThemeToggle: typeof import('./src/components/ui/KqcThemeToggle.vue')['default']
    KqcToast: typeof import('./src/components/ui/KqcToast.vue')['default']
    MetricsDashboard: typeof import('./src/components/admin/MetricsDashboard.vue')['default']
    PublicBreadcrumb: typeof import('./src/components/layout/PublicBreadcrumb.vue')['default']
    PublicFaqModal: typeof import('./src/components/public/PublicFaqModal.vue')['default']
    PublicLayout: typeof import('./src/components/layout/PublicLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/showcase/ServiceCard.vue')['default']
    SidebarMenuItem: typeof import('./src/components/layout/sidebar/SidebarMenuItem.vue')['default']
    SidebarNav: typeof import('./src/components/layout/sidebar/SidebarNav.vue')['default']
    StatsDashboard: typeof import('./src/components/admin/StatsDashboard.vue')['default']
    StructuredArticleContent: typeof import('./src/components/insights/StructuredArticleContent.vue')['default']
    StructuredArticleEditor: typeof import('./src/components/admin/articles/StructuredArticleEditor.vue')['default']
  }
}
