import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const root = new URL('../../', import.meta.url)
const read = (path) => readFileSync(new URL(path, root), 'utf8')

// ============================================================
// Industry Insights — Public Article List Contract
// WEB-1F-D2B
// ============================================================
test('public list uses the existing bounded Article endpoint and eight-item pagination', () => {
  const api = read('src/api/publicArticles.ts'); const view = read('src/views/InsightsView.vue')
  const listItemType = api.slice(api.indexOf('export interface PublicArticleListItem'), api.indexOf('export interface PublicArticleListResponse'))
  assert.match(api, /import api from '\.\/axios'/)
  assert.match(api, /api\.get<Envelope<PublicArticleListResponse>>\('\/public\/articles'/)
  assert.match(api, /params: \{ page, limit, \.\.\.\(category \? \{ category \} : \{\}\), \.\.\.\(featured !== undefined \? \{ featured \} : \{\}\) \}/)
  assert.match(view, /const PAGE_SIZE = 8/)
  assert.match(view, /publicArticlesApi\.list\(\{ page: page\.value, limit: PAGE_SIZE, category: activeCategory\.value \}\)/)
  assert.doesNotMatch(listItemType, /content:\s*string/)
  assert.doesNotMatch(`${api}\n${view}`, /adminArticlesApi|hardcodedArticles|demoArticles|JSON\.stringify/)
  assert.doesNotMatch(api, /scheduledAt|creatorDisplayName|createdBy/)
})

test('featured articles use the complete published public filter above category controls', () => {
  const api = read('src/api/publicArticles.ts'); const view = read('src/views/InsightsView.vue')
  assert.match(api, /featured\?: boolean/)
  assert.match(view, /const FEATURED_PAGE_SIZE = 100/)
  assert.match(view, /publicArticlesApi\.list\(\{ page: featuredPage, limit: FEATURED_PAGE_SIZE, featured: true \}\)/)
  assert.match(view, /collected\.push\(\.\.\.response\.data\.articles\.filter\(\(article\) => article\.isFeatured === true\)\)/)
  assert.match(view, /while \(featuredPage <= totalPages\)/)
  assert.match(view, /<section v-if="featuredArticles\.length" class="featured-articles"/)
  assert.ok(view.indexOf('class="featured-articles"') < view.indexOf('class="article-filters"'))
  assert.match(view, /:loop="featuredArticles\.length > 1"/)
  assert.match(view, /:navigation="featuredArticles\.length > 1"/)
  assert.match(view, /:pagination="featuredArticles\.length > 1 \? \{ clickable: true \} : false"/)
  assert.match(view, /<RouterLink :to="`\/insights\/\$\{article\.slug\}`" class="featured-article-card">/)
  assert.match(view, /Promise\.all\(\[loadArticles\(\), loadFeaturedArticles\(\)\]\)/)
})

test('seven visible filters map to exactly six canonical categories and all sends no category', () => {
  const api = read('src/api/publicArticles.ts'); const view = read('src/views/InsightsView.vue')
  const filters = view.slice(view.indexOf("  { label: '全部文章'"), view.indexOf('const categoryLabels'))
  for (const label of ['全部文章', '經營管理', '運輸小知識', '市場趨勢', '政策法規', 'KQC 快訊', '事業轉型']) assert.ok(filters.includes(`'${label}'`))
  assert.equal((filters.match(/label:/g) ?? []).length, 7)
  assert.equal((filters.match(/category:/g) ?? []).length, 6)
  assert.match(filters, /\{ label: '全部文章' \}/)
  assert.doesNotMatch(`${api}\n${filters}`, /DIGITAL_TRANSFORMATION|PRACTICAL_GUIDE|CASE_INSIGHT|ALL_ARTICLES|'ALL'/)
  const categoryType = api.match(/export type PublicArticleCategory = ([^\r\n]+)/)?.[1] ?? ''
  assert.equal((categoryType.match(/'[A-Z_]+'/g) ?? []).length, 6)
  assert.match(view, /const canonicalCategories = new Set<PublicArticleCategory>/)
  assert.match(view, /canonicalCategories\.has\(value as PublicArticleCategory\)/)
  assert.match(view, /activeCategory = ref<PublicArticleCategory \| undefined>\(categoryFromQuery\(route\.query\.category\)\)/)
  assert.match(view, /if \(category\) query\.category = category[\s\S]*else delete query\.category[\s\S]*router\.push\(\{ name: 'Insights', query, hash: route\.hash \}\)/)
  assert.match(view, /watch\(\(\) => route\.query\.category, async \(value\) => \{[\s\S]*activeCategory\.value = category[\s\S]*page\.value = 1[\s\S]*await loadArticles\(\)/)
  assert.match(view, /value !== undefined && category === undefined[\s\S]*delete query\.category[\s\S]*router\.replace/)
  assert.doesNotMatch(view, /window\.location|history\.pushState|localStorage|sessionStorage|tab=|category=KQC 快訊/)
  // D2H-R2 — Insights Article Scroll Target is one-shot and layout-safe, never a general category-navigation side effect.
  assert.match(view, /id="insights-articles" ref="articleScrollTarget" class="insights-article-region"/)
  assert.match(view, /if \(!articleScrollHandled && route\.hash === '#insights-articles'\)/)
  assert.match(view, /const scrollToArticleListAnchor = async \(epoch: number\) => \{[\s\S]*await nextTick\(\)[\s\S]*await nextAnimationFrame\(\)[\s\S]*await nextAnimationFrame\(\)/)
  assert.match(view, /const categoryNavTarget = ref<HTMLElement \| null>\(null\)/)
  assert.match(view, /<nav ref="categoryNavTarget" class="article-filters"/)
  assert.match(view, /navRect = categoryNavTarget\.value\.getBoundingClientRect\(\)/)
  assert.match(view, /querySelector<HTMLElement>\('\.kqc-sticky-header'\)[^\n]*getBoundingClientRect\(\)/)
  assert.match(view, /headerBottom = Math\.max\(headerRect\?\.bottom \?\? 0, 0\)[\s\S]*desiredGap = 28[\s\S]*targetTop = window\.scrollY \+ navRect\.top - headerBottom - desiredGap/)
  assert.match(view, /window\.scrollTo\(\{ top: Math\.max\(0, targetTop\), behavior: 'auto' \}\)/)
  assert.match(view, /await nextAnimationFrame\(\)[\s\S]*epoch !== articleNavigationScrollEpoch[\s\S]*expectedTop = Math\.max\(settledHeaderRect\?\.bottom \?\? 0, 0\) \+ desiredGap[\s\S]*finalNavTop = categoryNavTarget\.value\.getBoundingClientRect\(\)\.top/)
  assert.match(view, /Math\.abs\(correction\) > 3[^\n]*window\.scrollTo\(\{ top: Math\.max\(0, window\.scrollY \+ correction\), behavior: 'auto' \}\)/)
  assert.match(view, /let articleNavigationScrollEpoch = 0[\s\S]*epoch !== articleNavigationScrollEpoch/)
  assert.match(view, /pendingCategoryScroll = \{ epoch: scrollEpoch, category \}[\s\S]*await router\.push/)
  assert.match(view, /await loadArticles\(\)[\s\S]*scrollToArticleListAnchor\(scrollRequest\.epoch\)/)
  assert.match(view, /activeCategory\.value === category[\s\S]*scrollToArticleListAnchor\(scrollEpoch\)/)
  assert.match(view, /articleScrollHandled = true[\s\S]*await scrollToArticleListHash\(\)/)
  const categoryScroll = view.slice(view.indexOf('const scrollToArticleListAnchor'), view.indexOf('const scrollToArticleListHash'))
  assert.doesNotMatch(categoryScroll, /scrollIntoView/)
  assert.match(view, /prefers-reduced-motion: reduce[\s\S]*\? 'auto' : 'smooth'/)
  assert.match(view, /\.insights-article-region \{ scroll-margin-top: 10\.5rem; \}/)
  assert.doesNotMatch(view, /scrollTo\s*\(\s*0\s*,|localStorage|sessionStorage/)
})

test('pagination waits for its page data and reuses the deterministic category anchor', () => {
  const view = read('src/views/InsightsView.vue')
  const pagination = view.slice(view.indexOf('const changePage'), view.indexOf('const formatDate'))
  assert.match(pagination, /const changePage = async/)
  assert.match(pagination, /scrollEpoch = \+\+articleNavigationScrollEpoch/)
  assert.match(pagination, /page\.value = Math\.max\(1, event\.page \+ 1\)[\s\S]*await loadArticles\(\)[\s\S]*await scrollToArticleListAnchor\(scrollEpoch\)/)
  assert.doesNotMatch(pagination, /activeCategory\.value\s*=|router\.(push|replace)/)
  assert.match(view, /<Paginator[\s\S]*?:first="\(page - 1\) \* PAGE_SIZE"[\s\S]*?@page="changePage"/)
})

test('cards use coverImage and slug navigation while detail ownership remains separate', () => {
  const view = read('src/views/InsightsView.vue'); const router = read('src/router/index.ts'); const detail = read('src/views/InsightsDetailView.vue')
  assert.match(view, /:to="`\/insights\/\$\{article\.slug\}`"/)
  assert.match(view, /v-if="article\.coverImage" :src="publicArticleCoverUrl\(article\.coverImage\)"/)
  for (const field of ['article.categories', 'article.title', 'article.publishedAt', 'article.summary']) assert.ok(view.includes(field))
  assert.match(view, /v-for="category in article\.categories"/)
  assert.match(view, /class="article-card__read-more">閱讀全文 →/)
  assert.doesNotMatch(view, /creatorDisplayName|createdBy|撰寫人|作者/)
  assert.match(router, /path: '\/insights\/:slug'[\s\S]{0,180}InsightsDetailView\.vue/)
  assert.match(detail, /Public Article Detail[\s\S]*WEB-1F-D2C/)
  assert.doesNotMatch(view, /v-html|article\.content|video|relatedArticles|related links|share|like|subscribe/i)
})

test('grid and media preserve four two one columns and a consistent sixteen-nine crop', () => {
  const view = read('src/views/InsightsView.vue'); const styles = view.slice(view.indexOf('<style'))
  assert.match(styles, /\.article-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/s)
  assert.match(styles, /@media \(max-width: \$breakpoint-lg\)[\s\S]*?\.article-grid \{[^}]*repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(styles, /@media \(max-width: \$breakpoint-sm\)[\s\S]*?\.article-grid \{[^}]*grid-template-columns: minmax\(0, 1fr\)/)
  assert.match(styles, /\.article-card__media[^}]*aspect-ratio: 16 \/ 9/s)
  assert.match(styles, /\.article-card__media img \{[^}]*object-fit: cover/s)
  assert.match(styles, /\.article-filters \{[^}]*overflow-x: auto/s)
  assert.doesNotMatch(styles, /\.article-card:hover[^}]*translateY|\.article-card:hover[^}]*box-shadow/s)
  assert.match(styles, /\.article-card:hover \.article-card__media img[^}]*transform: scale\(1\.04\)/s)
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[^}]*article-card__media img[^}]*transition: none/s)
})

test('loading empty error and explicit retry states remain production-data driven', () => {
  const view = read('src/views/InsightsView.vue')
  assert.match(view, /v-if="loading && !initialLoadComplete"[^>]*aria-label="文章載入中"/)
  assert.match(view, /v-if="loading && initialLoadComplete"[^>]*role="status">正在更新文章…/)
  assert.match(view, /initialLoadComplete\.value = true/)
  assert.match(view, /v-else-if="errorMessage"[^>]*role="alert"/)
  assert.match(view, /label="重新載入"[^>]*@click="loadArticles"/)
  assert.match(view, /v-else-if="!articles\.length"/)
  assert.match(view, /目前尚無文章/)
  assert.match(view, /catch \{[\s\S]*?文章載入失敗，請稍後再試。/)
  assert.doesNotMatch(view, /setInterval|setTimeout|fake|mock|seed/i)
})

test('category controls are centered without sacrificing bounded horizontal overflow and page spacing is locally compact', () => {
  const view = read('src/views/InsightsView.vue')
  assert.match(view, /class="article-filters__inner"/)
  assert.match(view, /\.article-filters \{[^}]*overflow-x: auto/s)
  assert.match(view, /\.article-filters__inner \{[^}]*width: max-content;[^}]*min-width: 100%;[^}]*justify-content: center;/s)
  assert.match(view, /class="insights-view insights-view--breadcrumb-compact"/)
  assert.match(view, /\.insights-view--breadcrumb-compact \{[^}]*padding-top: \$kqc-spacing-xl;/s)
})
