import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const root = new URL('../../', import.meta.url)
const read = (path) => readFileSync(new URL(path, root), 'utf8')

test('current User models canonical multi-capabilities without JWT or storage authority', () => {
  const auth = read('src/api/auth.ts')
  const helpers = read('src/config/capabilities.ts')
  const store = read('src/stores/authStore.ts')
  assert.match(auth, /capabilities\?: Capability\[\]/)
  for (const capability of ['MEMBER', 'SALES', 'SALES_SUPERVISOR', 'PLATFORM_MANAGER', 'ADMIN']) assert.match(helpers, new RegExp(capability))
  assert.match(helpers, /normalized\.has\('SALES_SUPERVISOR'\)[\s\S]{0,80}normalized\.add\('SALES'\)/)
  assert.match(helpers, /Array\.isArray\(user\.capabilities\)[\s\S]{0,100}LEGACY_ROLE_CAPABILITIES/)
  assert.match(store, /hasCapability\(user\.value, 'ADMIN'\)/)
  assert.doesNotMatch(`${helpers}\n${store}`, /localStorage|sessionStorage|decode|jwt/i)
})

test('route and Sidebar governance access use capability metadata', () => {
  const router = read('src/router/index.ts')
  const menu = read('src/config/sidebarMenu.ts')
  const nav = read('src/components/layout/sidebar/SidebarNav.vue')
  assert.match(router, /const requiredCapabilities = to\.meta\.capabilities/)
  assert.match(router, /!hasAnyCapability\(authStore\.user, requiredCapabilities\)/)
  assert.match(router, /path: 'invitations'[\s\S]{0,180}capabilities: \['ADMIN'\]/)
  assert.match(router, /path: 'organizations'[\s\S]{0,220}SALES_SUPERVISOR[\s\S]{0,80}PLATFORM_MANAGER/)
  assert.match(menu, /id: 'organizations'[\s\S]{0,160}capabilities:/)
  assert.match(nav, /hasAnyCapability\(authStore\.user, item\.capabilities\)/)
})

test('account categories send authoritative capability filters and never filter paged rows locally', () => {
  const config = read('src/config/adminUsers.ts')
  const api = read('src/api/adminUsers.ts')
  const view = read('src/views/admin/users/AdminUsersView.vue')
  for (const mapping of ["members: { capability: 'MEMBER'", "sales: { capability: 'SALES'",
    "managers: { capability: 'PLATFORM_MANAGER'", "admins: { capability: 'ADMIN'"]) assert.match(config, new RegExp(mapping.replace(/[{}]/g, '\\$&')))
  assert.match(api, /AdminUserListQuery[\s\S]{0,180}capability: Capability/)
  assert.match(view, /capability: section\.value\.capability/)
  assert.match(view, /search: search\.value \|\| undefined[\s\S]{0,80}status: status\.value/)
  assert.doesNotMatch(view, /users\.value\s*=\s*response\.data\.users\.filter/)
})

test('account detail and permission governance reload authoritative user and assignment state', () => {
  const api = read('src/api/adminUsers.ts')
  const view = read('src/views/admin/users/AdminUsersView.vue')
  assert.match(api, /organization-assignments/)
  assert.match(api, /\/capabilities`, \{ capabilities \}/)
  assert.match(view, /openUserDetail[\s\S]{0,800}adminUsersApi\.assignments\(userId\)/)
  assert.doesNotMatch(view.slice(0, view.indexOf('const openUserDetail')), /adminUsersApi\.assignments/)
  assert.match(view, /身份 \/ 職能/)
  assert.match(view, /目前組織職務/)
  assert.match(view, /await adminUsersApi\.changeCapabilities/)
  assert.match(view, /Promise\.all\(\[loadGovernance\(userId\), loadUsers\(\)\]\)/)
  assert.match(view, /Promise\.all\(\[loadGovernance\(userId\), loadUsers\(\)\]\)/)
  assert.match(view, /LAST_USABLE_ADMIN/)
})

test('Staff Invitation uses capability choices, excludes MEMBER, and supports optional organization assignment', () => {
  const api = read('src/api/adminInvitations.ts')
  const view = read('src/views/admin/invitations/AdminInvitationsView.vue')
  const helpers = read('src/config/capabilities.ts')
  for (const method of ['list', 'create', 'resend', 'revoke']) assert.match(api, new RegExp(`${method}:`))
  assert.match(view, /filter\(\(item\) => item !== 'MEMBER'\)/)
  for (const capability of ['SALES_SUPERVISOR', 'PLATFORM_MANAGER', 'ADMIN']) assert.match(helpers, new RegExp(capability))
  assert.match(view, /organizationUnitId/)
  assert.match(view, /assignmentRole/)
  assert.match(view, /沿用既有帳號[\s\S]{0,80}不會建立重複 User/)
  assert.match(view, /mailDelivered/)
  assert.match(view, /await load\(\)/)
})

test('Organization UI reads assignments and supports scoped authoritative mutations', () => {
  const api = read('src/api/adminOrganizations.ts')
  const view = read('src/views/admin/organizations/AdminOrganizationsView.vue')
  for (const method of ['list', 'assignments', 'assignmentCandidates', 'create', 'update', 'assign', 'remove', 'move']) assert.match(api, new RegExp(`${method}:`))
  assert.match(view, /loadAssignments/)
  assert.match(view, /assignmentRole === 'supervisor' \? '主管' : '成員'/)
  assert.match(view, /authStore\.isAdmin/)
  assert.match(view, /status === 'disabled'/)
  assert.match(view, /不可新增成員、主管或作為移動目的地/)
  assert.match(view, /沒有此組織的管理範圍/)
  assert.match(view, /status === 409[\s\S]{0,100}primary/)
  assert.match(view, /reloadAuthoritative/)
  assert.match(view, /await loadOrganizations\(\)/)
  assert.match(view, /await loadAssignments\(current\)/)
})

test('Organization UI distinguishes account capability from assignment role and exposes multi-role data', () => {
  const view = read('src/views/admin/organizations/AdminOrganizationsView.vue')
  assert.match(view, /部門成員/)
  assert.match(view, /部門主管/)
  assert.match(view, /data\.user\?\.capabilities/)
  assert.match(view, /data\.assignmentRole/)
  assert.match(view, /data\.isPrimary/)
  assert.match(view, /destinationOptions/)
  assert.doesNotMatch(view, /type="checkbox"[^>]*isPrimary|v-model="[^\"]*isPrimary"/)
})

test('Organization assignment picker uses scoped candidate API and submits only selected candidate id', () => {
  const api = read('src/api/adminOrganizations.ts')
  const view = read('src/views/admin/organizations/AdminOrganizationsView.vue')
  assert.match(api, /AssignmentCandidateQuery[\s\S]{0,160}assignmentRole: AssignmentRole[\s\S]{0,100}search\?: string[\s\S]{0,80}page: number[\s\S]{0,80}limit: number/)
  assert.match(api, /\/assignment-candidates`[\s\S]{0,80}\{ params: query \}/)
  assert.doesNotMatch(view, /<label>User ID|v-model="assignForm\.userId"/)
  assert.doesNotMatch(view, /adminUsersApi|\/admin\/users/)
  assert.match(view, /candidate\.name/)
  assert.match(view, /candidate\.email/)
  assert.match(view, /candidate\.capabilities[\s\S]{0,120}capabilityLabel/)
  assert.match(view, /selectedCandidate\.value = candidate/)
  assert.match(view, /userId: selectedCandidate\.value\.id/)
  assert.doesNotMatch(view, /userId:\s*candidateSearch/)
  assert.match(view, /!selectedCandidate \|\| assignmentSubmitting/)
})

test('Organization picker invalidates selection by role/search, blocks stale responses, and paginates', () => {
  const view = read('src/views/admin/organizations/AdminOrganizationsView.vue')
  const roleHandler = view.slice(view.indexOf('const changeAssignmentRole'), view.indexOf('const selectCandidate'))
  assert.match(roleHandler, /selectedCandidate\.value = null/)
  assert.match(roleHandler, /candidates\.value = \[\]/)
  assert.match(roleHandler, /candidatePage\.value = 1/)
  assert.match(roleHandler, /loadCandidates\(\)/)
  assert.match(view, /watch\(candidateSearch[\s\S]{0,220}candidatePage\.value = 1[\s\S]{0,100}loadCandidates\(\)/)
  assert.match(view, /setTimeout\([\s\S]{0,180}, 300\)/)
  assert.match(view, /request !== candidateRequestId[\s\S]{0,220}candidateSearch\.value !== search/)
  assert.match(view, /assignmentRole, search: search \|\| undefined, page, limit:/)
  assert.match(view, /changeCandidatePage/)
  assert.match(view, /candidatePagination\.totalPages > 1/)
  assert.match(view, /正在載入符合條件的使用者/)
  assert.match(view, /找不到符合目前指派條件的使用者/)
  assert.match(view, /status === 403|response\?\.status === 403/)
  assert.match(view, /status === 409|response\?\.status === 409/)
  assert.match(view, /status === 422|response\?\.status === 422/)
})

test('Organization picker defaults by domain and never offers unsupported platform member role', () => {
  const view = read('src/views/admin/organizations/AdminOrganizationsView.vue')
  assert.match(view, /selected\.value\?\.domain === 'platform' \? 'supervisor' : 'member'/)
  assert.match(view, /selected\.value\?\.domain === 'platform'[\s\S]{0,100}\[\{ label: '部門主管', value: 'supervisor'/)
  assert.match(view, /平台組織目前僅支援部門主管指派/)
  assert.doesNotMatch(view, /platform worker|platform operator/i)
  assert.match(view, /await reloadAuthoritative\(\)/)
  assert.match(view, /removeAssignment/)
  assert.match(view, /moveAssignment/)
})
